name: julia-nightly

on:
  push:
    branches: [master]
    tags: ['**']
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['nightly']

    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v3
        with:
          delete-old-caches: 'false'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          depwarn: 'no'
          coverage: 'false'
